# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0lFm4iEP5979oXIMM-JuBuwyCP9182c
"""

# ==============================
# Resume Screening AI for Colab
# TF-IDF + XGBoost + PDF/DOCX extraction
# ==============================

# ---- CELL 1: Install packages ----
!pip -q install pandas scikit-learn xgboost pypdf2 python-docx

# ---- CELL 2: Imports ----
import os
import re
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np
import pandas as pd
from PyPDF2 import PdfReader
from docx import Document

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.metrics.pairwise import cosine_similarity

from xgboost import XGBClassifier

# ---- CELL 3: Text cleaning ----
STOPWORDS = {
    "a", "an", "the", "and", "or", "but", "if", "while", "is", "am", "are", "was", "were",
    "be", "been", "being", "to", "of", "in", "for", "on", "with", "as", "by", "at", "from",
    "this", "that", "these", "those", "it", "its", "into", "about", "over", "after", "before",
    "between", "during", "without", "within", "through", "can", "could", "should", "would",
    "may", "might", "will", "just", "also", "we", "you", "they", "he", "she", "i", "me",
    "my", "our", "your", "their", "them", "us", "who", "whom", "which", "what", "where",
    "when", "why", "how", "not", "no", "yes"
}

def clean_text(text: str) -> str:
    if not isinstance(text, str):
        text = "" if text is None else str(text)
    text = text.lower()
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    tokens = [t for t in text.split() if t not in STOPWORDS and len(t) > 1]
    return " ".join(tokens)

# ---- CELL 4: PDF / DOCX text extraction ----
def extract_text_from_pdf(pdf_path: str) -> str:
    reader = PdfReader(pdf_path)
    parts = []
    for page in reader.pages:
        page_text = page.extract_text() or ""
        if page_text.strip():
            parts.append(page_text)
    return "\n".join(parts).strip()

def extract_text_from_docx(docx_path: str) -> str:
    document = Document(docx_path)
    parts = []
    for para in document.paragraphs:
        if para.text.strip():
            parts.append(para.text)
    return "\n".join(parts).strip()

def extract_resume_text(file_path: str) -> str:
    ext = os.path.splitext(file_path)[1].lower()
    if ext == ".pdf":
        return extract_text_from_pdf(file_path)
    elif ext == ".docx":
        return extract_text_from_docx(file_path)
    else:
        raise ValueError("Unsupported file type. Upload a PDF or DOCX file.")

# ---- CELL 5: Demo training data ----
def build_demo_dataset() -> pd.DataFrame:
    data = [
        {
            "resume_text": "Computer Science student skilled in Python, SQL, pandas, NumPy, machine learning, data analysis, and web development. Experience with Google Colab, MySQL, APIs, GitHub, and problem solving.",
            "job_description": "Looking for a Python developer with machine learning, SQL, data analysis, pandas, NumPy, and web development skills.",
            "label": 1,

        },
        {
            "resume_text": "Computer Science pre-final year student with Python, SQL, web development, Shopify development, LinkedIn Sales Navigator outreach, and data labeling experience.",
            "job_description": "Hiring a technical intern with Python, SQL, web development, and communication skills.",
            "label": 1

        },
        {
            "resume_text": "Graphic designer with Photoshop, Illustrator, branding, logo design, and animation skills.",
            "job_description": "Hiring a backend Python developer with APIs and machine learning experience.",
            "label": 0,

        },

    ]
    return pd.DataFrame(data)

# ---- CELL 6: Model setup ----
@dataclass
class TrainedModel:
    pipeline: Pipeline
    accuracy: float
    report: str
    matrix: np.ndarray

def make_pipeline() -> Pipeline:
    cleaner = FunctionTransformer(lambda df: df.applymap(clean_text), validate=False)

    features = ColumnTransformer(
        transformers=[
            ("resume_tfidf", TfidfVectorizer(max_features=3000, ngram_range=(1, 2)), "resume_text"),
            ("job_tfidf", TfidfVectorizer(max_features=3000, ngram_range=(1, 2)), "job_description"),
        ]
    )

    model = XGBClassifier(
        n_estimators=250,
        max_depth=4,
        learning_rate=0.08,
        subsample=0.9,
        colsample_bytree=0.9,
        reg_lambda=1.0,
        random_state=42,
        eval_metric="logloss",
        n_jobs=4,
    )

    return Pipeline([
        ("cleaner", cleaner),
        ("features", features),
        ("classifier", model),
    ])

def train_model(df: pd.DataFrame) -> TrainedModel:
    required_cols = {"resume_text", "job_description", "label"}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {', '.join(sorted(missing))}")

    data = df.copy()
    data["resume_text"] = data["resume_text"].fillna("").astype(str)
    data["job_description"] = data["job_description"].fillna("").astype(str)
    data["label"] = data["label"].astype(int)

    X = data[["resume_text", "job_description"]]
    y = data["label"]

    stratify = y if y.nunique() > 1 and y.value_counts().min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=stratify
    )

    pipeline = make_pipeline()
    pipeline.fit(X_train, y_train)

    y_pred = pipeline.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred, zero_division=0)
    matrix = confusion_matrix(y_test, y_pred)

    return TrainedModel(
        pipeline=pipeline,
        accuracy=acc,
        report=report,
        matrix=matrix,
    )

# ---- CELL 7: Prediction helpers ----


def score_resume(pipeline, resume_text, job_description):
    resume_clean = clean_text(resume_text)
    job_clean = clean_text(job_description)

    # cosine similarity between resume and job description
    tfidf = TfidfVectorizer(ngram_range=(1, 2))
    tfidf_matrix = tfidf.fit_transform([resume_clean, job_clean])
    cosine_score = float(cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])[0][0])

    # keyword overlap
    resume_words = set(resume_clean.split())
    job_words = set(job_clean.split())
    overlap_score = len(resume_words.intersection(job_words)) / max(len(job_words), 1)

    # important skill bonus
    important_skills = {
        "python", "sql", "pandas", "numpy", "mysql", "web",
        "development", "data", "analysis", "machine", "learning",
        "colab", "github", "api", "apis"
    }
    skill_bonus = len(resume_words.intersection(important_skills)) * 0.05

    # final score
    final_score = (0.60 * cosine_score) + (0.30 * overlap_score) + skill_bonus
    final_score = min(final_score, 1.0)

    prediction = 1 if final_score >= 0.35 else 0
    return prediction, final_score


def rank_resumes(pipeline, resumes, job_description):
    rows = []

    for r in resumes:
        pred, score = score_resume(pipeline, r, job_description)
        rows.append({
            "resume_text": r,
            "match_score": round(score * 100, 2)
        })

    result = pd.DataFrame(rows).sort_values("match_score", ascending=False)
    return result.reset_index(drop=True)

# ---- CELL 8: Train on demo data OR your own CSV ----
# Option A: use demo dataset
df = build_demo_dataset()

# Option B: use your own CSV dataset
# df = pd.read_csv("/content/your_training_dataset.csv")

trained = train_model(df)
print("Accuracy:", f"{trained.accuracy:.2%}")
print("\nClassification Report:\n", trained.report)
print("\nConfusion Matrix:\n", trained.matrix)

# ---- CELL 9: Upload resume PDF/DOCX and extract text ----
from google.colab import files

uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file:", filename)

resume_text = extract_resume_text(filename)
print("\nExtracted resume text preview:\n")
print(resume_text[:2000])

# ---- CELL 10: Predict single resume match ----
job_description = """
Looking for a Python developer / data analyst intern with Python, SQL, pandas,
NumPy, data analysis, web development, MySQL, Google Colab, and problem-solving skills.
"""

prediction,probability = score_resume(trained.pipeline, resume_text, job_description)

print("\nPrediction:", "Shortlist" if prediction == 1 else "Reject")
print(f"Match Score: {probability * 100:.2f}%")

# ---- CELL 11: R
resumes = [
    resume_text,
    "Python developer with experience in machine learning, pandas, SQL, and web development.",
    "Data analyst skilled in SQL, pandas, NumPy, and reporting.",
    "Sales executive with client handling and communication skills.",
    "Graphic designer with branding and poster design skills."
]



ranked = rank_resumes(trained.pipeline, resumes, job_description)
print(ranked)